
package service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UserService", targetNamespace = "http://metier/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserService {


    /**
     * 
     * @param id
     * @param name
     * @param email
     * @param password
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateUser", targetNamespace = "http://metier/", className = "service.UpdateUser")
    @ResponseWrapper(localName = "updateUserResponse", targetNamespace = "http://metier/", className = "service.UpdateUserResponse")
    @Action(input = "http://metier/UserService/updateUserRequest", output = "http://metier/UserService/updateUserResponse")
    public String updateUser(
        @WebParam(name = "name", targetNamespace = "")
        String name,
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "email", targetNamespace = "")
        String email,
        @WebParam(name = "password", targetNamespace = "")
                String password,
        @WebParam(name = "gender", targetNamespace = "")
                String Gender,
        @WebParam(name = "Image", targetNamespace = "")
                String image,
        @WebParam(name = "code", targetNamespace = "")
                String Code,
        @WebParam(name = "Status", targetNamespace = "")
                String status,
        @WebParam(name = "Type", targetNamespace = "")
                int type,
        @WebParam(name = "id", targetNamespace = "")
        int id);

    /**
     * 
     * @return
     *     returns java.util.List<service.User>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllUser", targetNamespace = "http://metier/", className = "service.GetAllUser")
    @ResponseWrapper(localName = "getAllUserResponse", targetNamespace = "http://metier/", className = "service.GetAllUserResponse")
    @Action(input = "http://metier/UserService/getAllUserRequest", output = "http://metier/UserService/getAllUserResponse")
    public List<User> getAllUser();

    /**
     * 
     * @param password
     * @param username
     * @param name
     * @param email
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addUser", targetNamespace = "http://metier/", className = "service.AddUser")
    @ResponseWrapper(localName = "addUserResponse", targetNamespace = "http://metier/", className = "service.AddUserResponse")
    @Action(input = "http://metier/UserService/addUserRequest", output = "http://metier/UserService/addUserResponse")
    public String addUser(
        @WebParam(name = "name", targetNamespace = "")
        String name,
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "email", targetNamespace = "")
        String email,
        @WebParam(name = "password", targetNamespace = "")
        String password);

    /**
     * 
     * @param password
     * @param username
     * @return
     *     returns service.User
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "userLogin", targetNamespace = "http://metier/", className = "service.UserLogin")
    @ResponseWrapper(localName = "userLoginResponse", targetNamespace = "http://metier/", className = "service.UserLoginResponse")
    @Action(input = "http://metier/UserService/userLoginRequest", output = "http://metier/UserService/userLoginResponse")
    public User userLogin(
        @WebParam(name = "username", targetNamespace = "")
        String username,
        @WebParam(name = "password", targetNamespace = "")
        String password);

    /**
     * 
     * @param id
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteUser", targetNamespace = "http://metier/", className = "service.DeleteUser")
    @ResponseWrapper(localName = "deleteUserResponse", targetNamespace = "http://metier/", className = "service.DeleteUserResponse")
    @Action(input = "http://metier/UserService/deleteUserRequest", output = "http://metier/UserService/deleteUserResponse")
    public String deleteUser(
        @WebParam(name = "id", targetNamespace = "")
        int id);

    void updateUser(String name, String email, String username, int id);
}
